---
title: "Model v0051 0.4 (localhost) Evaluation"
author: "Alexander V. Alekseyenko (Adapted by Paul M. Heider)"
date: "`r date()`"
output: 
  html_document: 
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: true
    df_print: paged
---

Run-specific parameters
```{r, Loading Parameters}
summer_filename <- "summer_batch_test_v0051_0.4_2021-05-27_localhost.tsv"
weekly_filename <- "weekly_batch_test_v0051_0.4_2021-05-26_localhost.tsv"
prodThreshold <- 0.2
maxRepls <- 50
dataPrefix <- "../data_final/v0051"
```

```{r child = 'evaluate_models_1-front-matter.Rmd', "Front Matter"}
```

```{r child = 'evaluate_models_2-data-summary.Rmd', "Data Summary"}
```

```{r child = 'evaluate_models_2b-test-data-summary.Rmd', "Data Summary"}
```

# Run simulation on training data

This is the slow step larger number of replicates will produce more stable estimates of the number of tests needed.
```{r, Run Simulation}
date()
trainingPerformance =
  evaluate_predictor_range( training_data$SysPred,
                            training_data$positive,
                            replicates = maxRepls , 
                            thgrid = NULL) 
date()
```

```{r child = 'evaluate_models_3a-train-performance.Rmd', "Train Performance Eval"}
```

```{r child = 'evaluate_models_3b-test-performance.Rmd', "Train Performance Eval"}
```

```{r child = 'evaluate_models_4-save-data.Rmd', "Train Performance Eval"}
```

